import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { AlertTriangle, BarChart3, CalendarDays, CircleDollarSign, FileBarChart, FileText, Package, PieChart as PieIcon, RefreshCw, ShoppingBag, Sparkles, TrendingDown, TrendingUp, Wallet, X, ExternalLink } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { supabase } from '@/api';
import { useLanguage } from '@/context/LanguageContext';
import { useAuth } from '@/context/AuthContext';
import { useBranchFilter } from '@/lib/useBranchFilter';
import { isAdminRole } from '@/lib/permissions';
import { useBranches } from '@/hooks/useBranches';
import { useSettings } from '@/context/SettingsContext';
import { formatCurrency, formatDateTime, formatNumber } from '@/lib/format';

type Range = 'today' | 'week' | 'month' | 'year';
type Sale = { id: string; invoice_number: string | null; total: number | null; created_at: string };
type Expense = { amount: number | null };
type Product = { name: string | null; low_stock_threshold?: number | null };
type Inventory = { quantity: number | null; product: Product[] | null };
type SaleItem = { quantity: number | null; total: number | null; product: Product[] | null };
type Point = { label: string; sales: number; expenses: number; invoices: number };
type ProductPoint = { name: string; value: number; quantity: number };

const ranges: Record<Range, [string, string]> = { today: ['اليوم', 'Today'], week: ['7 أيام', '7 Days'], month: ['30 يوم', '30 Days'], year: ['سنة', 'Year'] };
const reportItems = [
  ['المبيعات', 'Sales', 'sales'], ['المبيعات حسب طريقة الدفع', 'Sales by Payment', 'sales_by_payment'], ['المبيعات حسب الموظف', 'Sales by Employee', 'sales_by_employee'], ['المبيعات حسب المنتج', 'Sales by Product', 'sales_by_product'], ['الفواتير التفصيلية', 'Detailed Invoices', 'detailed_invoices'], ['المشتريات', 'Purchases', 'purchases'], ['المصروفات', 'Expenses', 'expenses'], ['الربحية', 'Profitability', 'profit'], ['المخزون', 'Inventory', 'inventory'], ['استهلاك المكونات', 'Component Consumption', 'component_consumption'], ['تكلفة الوصفات', 'Recipe Costs', 'recipe_costs'], ['أكثر المكونات استهلاكًا', 'Top Components', 'top_consumed_components'], ['أكثر المنتجات استهلاكًا', 'Top Consumed Products', 'top_consumed_products'], ['المخزون المنخفض', 'Low Stock', 'low_stock'],
] as const;
function Card({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-navy-800 dark:bg-navy-900 ${className}`}>{children}</section>; }
function Metric({ title, value, icon, tone, hint, href }: { title: string; value: string; icon: ReactNode; tone: string; hint: string; href: string }) { return <Link to={href}><Card className="relative overflow-hidden p-5 transition hover:-translate-y-0.5 hover:shadow-md"><div className={`absolute inset-x-0 top-0 h-1 ${tone}`} /><div className={`flex h-11 w-11 items-center justify-center rounded-xl ${tone} text-white`}>{icon}</div><p className="mt-4 text-sm font-medium text-slate-500 dark:text-slate-400">{title}</p><p className="mt-1 text-2xl font-bold text-slate-900 dark:text-white">{value}</p><p className="mt-1 text-xs text-slate-400">{hint}</p></Card></Link>; }
function Empty({ ar }: { ar: boolean }) { return <div className="flex h-full min-h-40 items-center justify-center text-sm text-slate-400">{ar ? 'لا توجد بيانات فعلية للفترة المحددة' : 'No actual data for the selected period'}</div>; }

export function DashboardEnhancedPage() {
  const { lang } = useLanguage(); const { user } = useAuth(); const { branches } = useBranches(); const branchFilter = useBranchFilter(); const { effectiveSettings } = useSettings(); const isAr = lang === 'ar';
  const [range, setRange] = useState<Range>('today'); const [branchId, setBranchId] = useState(''); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [reportsOpen, setReportsOpen] = useState(false);
  const [sales, setSales] = useState<Sale[]>([]); const [expenses, setExpenses] = useState<Expense[]>([]); const [inventory, setInventory] = useState<Inventory[]>([]); const [items, setItems] = useState<SaleItem[]>([]);
  const effectiveBranch = isAdminRole(user?.role) ? (branchId || null) : branchFilter; const settings = effectiveSettings(effectiveBranch); const currency = settings?.currency || 'EGP';

  const load = useCallback(async () => {
    setRefreshing(true);
    try {
      const end = new Date(); const start = new Date(end);
      if (range === 'today') start.setHours(0, 0, 0, 0); else if (range === 'week') start.setDate(start.getDate() - 6); else if (range === 'month') start.setDate(start.getDate() - 29); else start.setFullYear(start.getFullYear() - 1);
      let salesQ = supabase.from('sales').select('id,invoice_number,total,created_at').gte('created_at', start.toISOString()).lte('created_at', end.toISOString()).order('created_at', { ascending: false });
      let expenseQ = supabase.from('expenses').select('amount').gte('expense_date', start.toISOString().slice(0, 10)).lte('expense_date', end.toISOString().slice(0, 10));
      let inventoryQ = supabase.from('inventory').select('quantity,product:products(name,low_stock_threshold)');
      if (effectiveBranch) { salesQ = salesQ.eq('branch_id', effectiveBranch); expenseQ = expenseQ.eq('branch_id', effectiveBranch); inventoryQ = inventoryQ.eq('branch_id', effectiveBranch); }
      const [sr, er, ir] = await Promise.all([salesQ, expenseQ, inventoryQ]);
      if (sr.error) throw sr.error; if (er.error) throw er.error; if (ir.error) throw ir.error;
      const nextSales = (sr.data ?? []) as Sale[]; setSales(nextSales); setExpenses((er.data ?? []) as Expense[]); setInventory((ir.data ?? []) as Inventory[]);
      if (nextSales.length) { const ids = nextSales.map(s => s.id); const result = await supabase.from('sale_items').select('quantity,total,product:products(name)').in('sale_id', ids).limit(10000); setItems(result.error ? [] : ((result.data ?? []) as unknown as SaleItem[])); } else setItems([]);
    } catch (error) { console.error('Dashboard load failed', error); setSales([]); setExpenses([]); setInventory([]); setItems([]); }
    finally { setLoading(false); setRefreshing(false); }
  }, [range, effectiveBranch]);
  useEffect(() => { void load(); }, [load]);

  const metrics = useMemo(() => { const salesTotal = sales.reduce((s, r) => s + Number(r.total || 0), 0); const expenseTotal = expenses.reduce((s, r) => s + Number(r.amount || 0), 0); const invoices = sales.length; const avg = invoices ? salesTotal / invoices : 0; const net = salesTotal - expenseTotal; const margin = salesTotal ? net / salesTotal * 100 : 0; const threshold = Number(settings?.low_stock_threshold ?? 5); const low = inventory.filter(r => Number(r.quantity || 0) < Number(r.product?.[0]?.low_stock_threshold ?? threshold)).length; return { salesTotal, expenseTotal, invoices, avg, net, margin, low }; }, [sales, expenses, inventory, settings]);
  const chart = useMemo(() => { const map = new Map<string, Point>(); sales.forEach(s => { const d = new Date(s.created_at); const key = range === 'year' ? `${d.getFullYear()}-${d.getMonth() + 1}` : d.toISOString().slice(0, 10); const p = map.get(key) ?? { label: key, sales: 0, expenses: 0, invoices: 0 }; p.sales += Number(s.total || 0); p.invoices += 1; map.set(key, p); }); expenses.forEach((e, i) => { const p = Array.from(map.values())[Math.min(i, Math.max(map.size - 1, 0))]; if (p) p.expenses += Number(e.amount || 0); }); return Array.from(map.entries()).sort(([a], [b]) => a.localeCompare(b)).map(([key, p]) => ({ ...p, label: range === 'year' ? key.split('-')[1] : new Date(`${key}T00:00:00`).toLocaleDateString(isAr ? 'ar-EG' : 'en-US', { day: 'numeric', month: 'short' }) })); }, [sales, expenses, range, isAr]);
  const topProducts = useMemo<ProductPoint[]>(() => { const map = new Map<string, ProductPoint>(); items.forEach(i => { const name = i.product?.[0]?.name || (isAr ? 'منتج غير مسمى' : 'Unnamed product'); const p = map.get(name) ?? { name, value: 0, quantity: 0 }; p.value += Number(i.total || 0); p.quantity += Number(i.quantity || 0); map.set(name, p); }); return Array.from(map.values()).sort((a, b) => b.value - a.value).slice(0, 8); }, [items, isAr]);
  const financialMix = useMemo(() => [{ name: isAr ? 'المبيعات' : 'Sales', value: metrics.salesTotal }, { name: isAr ? 'المصروفات' : 'Expenses', value: metrics.expenseTotal }].filter(x => x.value > 0), [metrics, isAr]);
  const lowStock = useMemo(() => inventory.filter(r => Number(r.quantity || 0) < Number(r.product?.[0]?.low_stock_threshold ?? settings?.low_stock_threshold ?? 5)).slice(0, 8), [inventory, settings]);
  const reportLinks = useMemo(() => reportItems.map(([ar, en, type]) => ({ title: isAr ? ar : en, href: `/reports?reportType=${encodeURIComponent(type)}` })), [isAr]);
  const money = (v: number | undefined) => formatCurrency(v ?? 0, currency, lang);

  if (loading) return <div className="flex min-h-[60vh] items-center justify-center"><RefreshCw className="h-8 w-8 animate-spin text-brand-600" /></div>;
  return <div className="space-y-6 pb-8">
    <div className="rounded-3xl bg-gradient-to-br from-navy-950 via-navy-900 to-slate-900 p-6 shadow-xl sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-2 flex items-center gap-2 text-sm text-gold-300"><Sparkles className="h-4 w-4" />{isAr ? 'لوحة التحليلات المتقدمة' : 'Advanced Analytics Dashboard'}</div><h1 className="text-3xl font-bold text-white">{user?.full_name || (isAr ? 'لوحة التحكم' : 'Dashboard')}</h1><p className="mt-1 text-sm text-slate-400">{isAr ? 'مؤشرات ورسوم مبنية على البيانات الفعلية فقط' : 'Indicators and charts based only on actual data'}</p></div><div className="flex items-center gap-3"><div className="rounded-2xl border border-white/10 bg-white/5 px-5 py-3"><p className="text-xs text-slate-400">{isAr ? 'صافي الفترة' : 'Period net'}</p><p className="text-xl font-bold text-white">{formatCurrency(metrics.net, currency, lang)}</p></div><Link to="/pos" className="inline-flex items-center gap-2 rounded-2xl bg-gold-500 px-5 py-3 text-sm font-bold text-navy-950"><ShoppingBag className="h-4 w-4" />{isAr ? 'بيع جديد' : 'New Sale'}</Link></div></div></div>
    <Card className="p-4"><div className="flex flex-wrap items-center gap-2"><CalendarDays className="h-4 w-4 text-brand-600" />{(Object.keys(ranges) as Range[]).map(r => <button key={r} onClick={() => setRange(r)} className={`rounded-xl px-4 py-2 text-sm font-semibold ${range === r ? 'bg-navy-900 text-white' : 'bg-slate-100 text-slate-600 dark:bg-navy-800 dark:text-slate-300'}`}>{ranges[r][isAr ? 0 : 1]}</button>)}{isAdminRole(user?.role) && branches.length > 0 && <select value={branchId} onChange={e => setBranchId(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-navy-700 dark:bg-navy-800 dark:text-slate-200"><option value="">{isAr ? 'كل الفروع' : 'All branches'}</option>{branches.map(b => <option key={b.id} value={b.id}>{isAr ? b.name : b.name_en || b.name}</option>)}</select>}<button onClick={() => void load()} className="ml-auto inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm"><RefreshCw className={`h-4 w-4 ${refreshing ? 'animate-spin' : ''}`} />{isAr ? 'تحديث' : 'Refresh'}</button><button onClick={() => setReportsOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-brand-600 px-4 py-2 text-sm font-bold text-white"><FileBarChart className="h-4 w-4" />{isAr ? 'كل التقارير' : 'All Reports'}</button></div></Card>
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-6"><Metric title={isAr ? 'إجمالي المبيعات' : 'Sales'} value={money(metrics.salesTotal)} icon={<CircleDollarSign className="h-5 w-5" />} tone="bg-gradient-to-br from-navy-800 to-navy-950" hint={`${metrics.invoices} ${isAr ? 'فاتورة' : 'invoices'}`} href="/reports?reportType=sales" /><Metric title={isAr ? 'المصروفات' : 'Expenses'} value={money(metrics.expenseTotal)} icon={<FileText className="h-5 w-5" />} tone="bg-gradient-to-br from-rose-500 to-rose-600" hint={isAr ? 'الفترة الحالية' : 'Current period'} href="/reports?reportType=expenses" /><Metric title={isAr ? 'صافي التشغيل' : 'Net'} value={money(metrics.net)} icon={<Wallet className="h-5 w-5" />} tone="bg-gradient-to-br from-gold-400 to-gold-600" hint={`${metrics.margin.toFixed(1)}% ${isAr ? 'هامش' : 'margin'}`} href="/reports?reportType=profit" /><Metric title={isAr ? 'الفواتير' : 'Invoices'} value={formatNumber(metrics.invoices, 0)} icon={<BarChart3 className="h-5 w-5" />} tone="bg-gradient-to-br from-brand-500 to-brand-700" hint={isAr ? 'طلبات فعلية' : 'Actual orders'} href="/reports?reportType=detailed_invoices" /><Metric title={isAr ? 'متوسط الفاتورة' : 'Average Ticket'} value={money(metrics.avg)} icon={<TrendingUp className="h-5 w-5" />} tone="bg-gradient-to-br from-emerald-500 to-emerald-600" hint={isAr ? 'المبيعات ÷ الفواتير' : 'Sales ÷ invoices'} href="/reports?reportType=sales" /><Metric title={isAr ? 'مخزون منخفض' : 'Low Stock'} value={formatNumber(metrics.low, 0)} icon={<AlertTriangle className="h-5 w-5" />} tone="bg-gradient-to-br from-amber-500 to-orange-500" hint={metrics.low ? (isAr ? 'يحتاج مراجعة' : 'Needs review') : (isAr ? 'لا يوجد' : 'None')} href="/reports?reportType=low_stock" /></div>
    <div className="grid grid-cols-1 gap-6 xl:grid-cols-3"><Card className="p-5 xl:col-span-2"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">{isAr ? 'اتجاه المبيعات والمصروفات' : 'Sales & Expenses Trend'}</h2><p className="text-xs text-slate-400">{isAr ? 'حركة الفترة المحددة' : 'Selected period movement'}</p></div><TrendingUp className="h-5 w-5 text-brand-600" /></div><div className="h-80">{chart.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="label" /><YAxis /><Tooltip formatter={(v: number | undefined) => money(v)} /><Area type="monotone" dataKey="sales" strokeWidth={3} fillOpacity={0.18} /><Area type="monotone" dataKey="expenses" strokeWidth={2} fillOpacity={0.08} /></AreaChart></ResponsiveContainer> : <Empty ar={isAr} />}</div></Card><Card className="p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">{isAr ? 'التوزيع المالي' : 'Financial Mix'}</h2><p className="text-xs text-slate-400">{isAr ? 'القيم الفعلية' : 'Actual values'}</p></div><PieIcon className="h-5 w-5 text-brand-600" /></div><div className="h-80">{financialMix.length ? <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={financialMix} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius={62} outerRadius={105} paddingAngle={3}>{financialMix.map((_, i) => <Cell key={i} /></Pie><Tooltip formatter={(v: number | undefined) => money(v)} /></PieChart></ResponsiveContainer> : <Empty ar={isAr} />}</div><div className="text-center text-sm text-slate-500">{isAr ? `الصافي: ${money(metrics.net)}` : `Net: ${money(metrics.net)}`}</div></Card></div>
    <div className="grid grid-cols-1 gap-6 xl:grid-cols-2"><Card className="p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">{isAr ? 'أفضل المنتجات' : 'Top Products'}</h2><p className="text-xs text-slate-400">{isAr ? 'حسب قيمة المبيعات الفعلية' : 'By actual sales value'}</p></div><Package className="h-5 w-5 text-brand-600" /></div><div className="h-80">{topProducts.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={topProducts} layout="vertical" margin={{ left: 20 }}><CartesianGrid strokeDasharray="3 3" /><XAxis type="number" /><YAxis type="category" dataKey="name" width={100} /><Tooltip formatter={(v: number | undefined) => money(v)} /><Bar dataKey="value" radius={[0, 6, 6, 0]} /></BarChart></ResponsiveContainer> : <Empty ar={isAr} />}</div><Link to="/reports?reportType=sales_by_product" className="mt-3 block text-center text-sm font-semibold text-brand-600">{isAr ? 'فتح تقرير المنتجات' : 'Open product report'}</Link></Card><Card className="p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">{isAr ? 'حجم الفواتير' : 'Invoice Volume'}</h2><p className="text-xs text-slate-400">{isAr ? 'عدد الطلبات عبر الفترة' : 'Order count across period'}</p></div><BarChart3 className="h-5 w-5 text-brand-600" /></div><div className="h-80">{chart.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="label" /><YAxis allowDecimals={false} /><Tooltip /><Bar dataKey="invoices" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer> : <Empty ar={isAr} />}</div></Card></div>
    <div className="grid grid-cols-1 gap-6 xl:grid-cols-2"><Card className="p-5"><div className="mb-4 flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-amber-500" /><h2 className="font-bold">{isAr ? 'الأصناف منخفضة المخزون' : 'Low Stock Items'}</h2></div>{lowStock.length ? <div className="space-y-2">{lowStock.map((row, i) => <div key={`${row.product?.[0]?.name}-${i}`} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 dark:bg-navy-800"><span className="truncate text-sm">{row.product?.[0]?.name || (isAr ? 'منتج غير مسمى' : 'Unnamed product')}</span><span className="font-bold text-amber-600">{formatNumber(Number(row.quantity || 0), 0)}</span></div>)}<Link to="/reports?reportType=low_stock" className="block pt-2 text-center text-sm font-semibold text-brand-600">{isAr ? 'عرض التقرير الكامل' : 'View full report'}</Link></div> : <Empty ar={isAr} />}</Card><Card className="p-5"><div className="mb-4 flex items-center gap-2"><Wallet className="h-5 w-5 text-brand-600" /><h2 className="font-bold">{isAr ? 'مؤشرات الأداء' : 'Performance Indicators'}</h2></div><div className="grid grid-cols-2 gap-3">{[[isAr ? 'هامش الصافي' : 'Net Margin', `${metrics.margin.toFixed(1)}%`, metrics.margin >= 0], [isAr ? 'المبيعات / الفاتورة' : 'Sales / Invoice', money(metrics.avg), true], [isAr ? 'المصروفات / المبيعات' : 'Expense Ratio', `${metrics.salesTotal ? (metrics.expenseTotal / metrics.salesTotal * 100).toFixed(1) : '0.0'}%`, metrics.expenseTotal <= metrics.salesTotal], [isAr ? 'الأصناف المنخفضة' : 'Low-stock Count', formatNumber(metrics.low, 0), metrics.low === 0]].map(([label, value, positive], i) => <div key={i} className="rounded-2xl border border-slate-200 p-4 dark:border-navy-700"><p className="text-xs text-slate-500">{label as string}</p><p className="mt-2 text-lg font-bold">{value as string}</p>{positive ? <TrendingUp className="mt-2 h-4 w-4 text-emerald-500" /> : <TrendingDown className="mt-2 h-4 w-4 text-rose-500" />}</div>)}</div></Card></div>
    <Card className="p-5"><div className="mb-4 flex items-center gap-2"><FileText className="h-5 w-5 text-brand-600" /><h2 className="font-bold">{isAr ? 'آخر المبيعات' : 'Recent Sales'}</h2></div>{sales.length ? <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-slate-500"><th className="px-3 py-3 text-start">{isAr ? 'الفاتورة' : 'Invoice'}</th><th className="px-3 py-3 text-start">{isAr ? 'التاريخ' : 'Date'}</th><th className="px-3 py-3 text-end">{isAr ? 'الإجمالي' : 'Total'}</th><th /></tr></thead><tbody>{sales.slice(0, 8).map(s => <tr key={s.id} className="border-b last:border-0"><td className="px-3 py-3">{s.invoice_number || s.id.slice(0, 8)}</td><td className="px-3 py-3 text-slate-500">{formatDateTime(s.created_at, lang)}</td><td className="px-3 py-3 text-end font-bold">{money(Number(s.total || 0))}</td><td className="px-3 py-3 text-end"><Link to={`/reports?reportType=detailed_invoices&saleId=${s.id}`}><ExternalLink className="inline h-4 w-4 text-brand-600" /></Link></td></tr>)}</tbody></table></div> : <Empty ar={isAr} />}</Card>
    {reportsOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" onMouseDown={e => { if (e.target === e.currentTarget) setReportsOpen(false); }}><div className="w-full max-w-3xl rounded-3xl bg-white p-6 shadow-2xl dark:bg-navy-900"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-bold">{isAr ? 'التقارير التفصيلية' : 'Detailed Reports'}</h2><p className="text-sm text-slate-500">{isAr ? 'اختر أي تقرير لفتح تفاصيله' : 'Choose a report to open its details'}</p></div><button onClick={() => setReportsOpen(false)} className="rounded-xl p-2 hover:bg-slate-100 dark:hover:bg-navy-800"><X /></button></div><div className="grid max-h-[65vh] grid-cols-1 gap-2 overflow-y-auto sm:grid-cols-2">{reportLinks.map(r => <Link key={r.href} to={r.href} onClick={() => setReportsOpen(false)} className="flex items-center gap-3 rounded-2xl border border-slate-200 p-4 font-semibold hover:border-brand-400 hover:bg-brand-50 dark:border-navy-700 dark:hover:bg-navy-800"><FileBarChart className="h-5 w-5 text-brand-600" />{r.title}</Link>)}</div></div></div>}
  </div>;
}
