import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { AlertTriangle, ChevronDown, Download, Filter, RefreshCw, ShoppingBag, Wallet, RotateCcw, Tag, CreditCard, Building2 } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { supabase } from '@/api';
import { useLanguage } from '@/context/LanguageContext';
import { useAuth } from '@/context/AuthContext';
import { useBranchFilter } from '@/lib/useBranchFilter';
import { isAdminRole } from '@/lib/permissions';
import { useBranches } from '@/hooks/useBranches';
import { useSettings } from '@/context/SettingsContext';
import { formatCurrency, formatNumber } from '@/lib/format';

type Range='today'|'week'|'month'|'year';
type Sale={id:string;invoice_number:string|null;total:number|null;paid_amount:number|null;payment_method:string|null;status:string|null;branch_id:string|null;created_at:string;order_type:string|null;refunded_amount?:number|null;discount_amount?:number|null;branch?:{name:string|null;name_en:string|null}[]|null};
type Expense={amount:number|null;expense_date:string|null};
type Inventory={quantity:number|null;product:{name:string|null;low_stock_threshold:number|null}[]|null};
type SaleItem={quantity:number|null;total:number|null;product:{name:string|null}[]|null};
type Point={label:string;sales:number;previous:number};
type Mix={name:string;value:number};
const ranges:Record<Range,[string,string]>={today:['اليوم','Today'],week:['الأسبوع','Week'],month:['الشهر','Month'],year:['السنة','Year']};
const paymentLabels:Record<string,[string,string]>={cash:['نقدي','Cash'],card:['بطاقة مدى','Card'],visa:['فيزا / ماستركارد','Visa / Mastercard'],bank:['تحويل بنكي','Bank Transfer'],instapay:['InstaPay','InstaPay'],wallet:['محفظة إلكترونية','Wallet'],other:['أخرى','Other']};
const reportItems=[['المبيعات','Sales','sales'],['المبيعات حسب طريقة الدفع','Sales by Payment','sales_by_payment'],['المبيعات حسب المنتج','Sales by Product','sales_by_product'],['المبيعات حسب الفرع','Sales by Branch','sales_by_branch'],['الفواتير التفصيلية','Detailed Invoices','detailed_invoices'],['المصروفات','Expenses','expenses'],['الربحية','Profitability','profit'],['المخزون','Inventory','inventory'],['المخزون المنخفض','Low Stock','low_stock']] as const;
function Card({children,className=''}:{children:ReactNode;className?:string}){return <section className={`rounded-2xl border border-slate-200 bg-white shadow-[0_3px_18px_rgba(15,23,42,0.05)] ${className}`}>{children}</section>}
function Empty({ar}:{ar:boolean}){return <div className="flex min-h-[160px] items-center justify-center text-sm text-slate-400">{ar?'لا توجد بيانات فعلية للفترة المحددة':'No actual data for selected period'}</div>}
function Metric({title,value,hint,icon,tone,href}:{title:string;value:string;hint:string;icon:ReactNode;tone:string;href:string}){return <Link to={href} className="block"><Card className="h-full p-5 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-slate-700">{title}</p><p className="mt-2 text-2xl font-bold tracking-tight text-slate-900">{value}</p><p className="mt-3 text-xs text-slate-500">{hint}</p></div><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl text-white ${tone}`}>{icon}</span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full w-2/3 rounded-full ${tone}`}/></div></Card></Link>}
export function DashboardFoodicsPage(){
 const {lang}=useLanguage();const {user}=useAuth();const {branches}=useBranches();const branchFilter=useBranchFilter();const {effectiveSettings}=useSettings();const isAr=lang==='ar';
 const [range,setRange]=useState<Range>('today');const [branchId,setBranchId]=useState('');const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [reportsOpen,setReportsOpen]=useState(false);const [exportOpen,setExportOpen]=useState(false);
 const [sales,setSales]=useState<Sale[]>([]);const [expenses,setExpenses]=useState<Expense[]>([]);const [inventory,setInventory]=useState<Inventory[]>([]);const [items,setItems]=useState<SaleItem[]>([]);
 const effectiveBranch=isAdminRole(user?.role)?(branchId||null):branchFilter;const settings=effectiveSettings(effectiveBranch);const currency=settings?.currency||'EGP';const money=(n:number)=>formatCurrency(n,currency,lang);
 const load=useCallback(async()=>{setRefreshing(true);try{const end=new Date();const start=new Date(end);if(range==='today')start.setHours(0,0,0,0);if(range==='week')start.setDate(start.getDate()-6);if(range==='month')start.setDate(start.getDate()-29);if(range==='year')start.setFullYear(start.getFullYear()-1);let q=supabase.from('sales').select('id,invoice_number,total,paid_amount,payment_method,status,branch_id,created_at,order_type,refunded_amount,discount_amount,branch:branches(name,name_en)').gte('created_at',start.toISOString()).lte('created_at',end.toISOString()).order('created_at',{ascending:false}).limit(5000);let eq=supabase.from('expenses').select('amount,expense_date').gte('expense_date',start.toISOString().slice(0,10)).lte('expense_date',end.toISOString().slice(0,10)).limit(5000);let iq=supabase.from('inventory').select('quantity,product:products(name,low_stock_threshold)').limit(5000);if(effectiveBranch){q=q.eq('branch_id',effectiveBranch);eq=eq.eq('branch_id',effectiveBranch);iq=iq.eq('branch_id',effectiveBranch)}const [sr,er,ir]=await Promise.all([q,eq,iq]);if(sr.error)throw sr.error;if(er.error)throw er.error;if(ir.error)throw ir.error;const rows=(sr.data??[]) as unknown as Sale[];setSales(rows);setExpenses((er.data??[]) as Expense[]);setInventory((ir.data??[]) as unknown as Inventory[]);if(rows.length){const r=await supabase.from('sale_items').select('quantity,total,product:products(name)').in('sale_id',rows.map(x=>x.id)).limit(10000);setItems(r.error?[]:(r.data??[]) as unknown as SaleItem[])}else setItems([])}catch(e){console.error('Dashboard load failed',e);setSales([]);setExpenses([]);setInventory([]);setItems([])}finally{setLoading(false);setRefreshing(false)}},[range,effectiveBranch]);
 useEffect(()=>{void load()},[load]);
 const metrics=useMemo(()=>{const salesTotal=sales.reduce((a,x)=>a+Number(x.total||0),0);const payments=sales.reduce((a,x)=>a+Number(x.paid_amount??x.total??0),0);const returns=sales.reduce((a,x)=>a+Number(x.refunded_amount||0),0);const discounts=sales.reduce((a,x)=>a+Number(x.discount_amount||0),0);const avg=sales.length?salesTotal/sales.length:0;return{salesTotal,payments,returns,discounts,orders:sales.length,avg,net:salesTotal-expenses.reduce((a,x)=>a+Number(x.amount||0),0)}},[sales,expenses]);
 const chart=useMemo<Point[]>(()=>{const map=new Map<string,Point>();sales.forEach(s=>{const d=new Date(s.created_at);const key=range==='year'?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`:d.toISOString().slice(0,10);const p=map.get(key)||{label:key,sales:0,previous:0};p.sales+=Number(s.total||0);map.set(key,p)});return [...map.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([key,p])=>({...p,label:range==='year'?key.slice(5):new Date(`${key}T00:00:00`).toLocaleDateString(isAr?'ar-EG':'en-US',{day:'numeric',month:'short'})}))},[sales,range,isAr]);
 const paymentMix=useMemo<Mix[]>(()=>{const map=new Map<string,number>();sales.forEach(s=>{const k=(s.payment_method||'other').toLowerCase();map.set(k,(map.get(k)||0)+Number(s.paid_amount??s.total??0))});return [...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([name,value])=>({name,value}))},[sales]);
 const topBranches=useMemo(()=>{const map=new Map<string,{name:string;orders:number;sales:number}>();sales.forEach(s=>{const b=s.branch?.[0];const name=isAr?(b?.name||'غير محدد'):(b?.name_en||b?.name||'Unknown');const p=map.get(name)||{name,orders:0,sales:0};p.orders++;p.sales+=Number(s.total||0);map.set(name,p)});return [...map.values()].sort((a,b)=>b.sales-a.sales).slice(0,5)},[sales,isAr]);
 const topProducts=useMemo(()=>{const map=new Map<string,{name:string;quantity:number}>();items.forEach(i=>{const name=i.product?.[0]?.name||'غير محدد';const p=map.get(name)||{name,quantity:0};p.quantity+=Number(i.quantity||0);map.set(name,p)});return [...map.values()].sort((a,b)=>b.quantity-a.quantity).slice(0,5)},[items]);
 const lowStock=useMemo(()=>inventory.filter(x=>Number(x.quantity||0)<Number(x.product?.[0]?.low_stock_threshold??settings?.low_stock_threshold??5)).slice(0,5),[inventory,settings]);const recent=sales.slice(0,5);const maxPayment=Math.max(...paymentMix.map(x=>x.value),1);const maxBranch=Math.max(...topBranches.map(x=>x.sales),1);const colors=['#5b2bd8','#2188e8','#17b26a','#f59e0b','#ec4899'];
 if(loading)return <div className="flex min-h-[60vh] items-center justify-center"><RefreshCw className="h-8 w-8 animate-spin text-brand-600"/></div>;
 return <div dir={isAr?'rtl':'ltr'} className="min-h-full bg-[#fafafa] pb-10 text-slate-900">
  <div className="sticky top-0 z-20 border-b border-slate-200 bg-white/95 px-5 py-4 backdrop-blur"><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-bold">{isAr?'لوحة التحكم':'Dashboard'}</h1><p className="mt-1 text-xs text-slate-500">{isAr?'نظرة شاملة على أداء النشاط':'A complete view of business performance'}</p></div><div className="flex flex-wrap items-center gap-2"><div className="flex rounded-xl border border-slate-200 bg-white p-1">{(Object.keys(ranges) as Range[]).map(r=><button key={r} onClick={()=>setRange(r)} className={`px-4 py-2 text-sm font-semibold ${range===r?'rounded-lg bg-brand-600 text-white':'text-slate-600'}`}>{ranges[r][isAr?0:1]}</button>)}</div><select value={branchId} onChange={e=>setBranchId(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm">{isAdminRole(user?.role)&&<option value="">{isAr?'كل الفروع':'All branches'}</option>}{branches.map(b=><option key={b.id} value={b.id}>{isAr?b.name:b.name_en||b.name}</option>)}</select><button onClick={()=>void load()} className="rounded-xl border border-slate-200 p-2.5"><RefreshCw className={refreshing?'h-4 w-4 animate-spin':'h-4 w-4'}/></button><button className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm"><Filter className="h-4 w-4"/>{isAr?'فلترة':'Filter'}</button><div className="relative"><button onClick={()=>setExportOpen(!exportOpen)} className="inline-flex items-center gap-2 rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-bold text-white"><Download className="h-4 w-4"/>{isAr?'تصدير التقرير':'Export Report'}<ChevronDown className="h-4 w-4"/></button>{exportOpen&&<div className="absolute end-0 top-12 z-30 w-52 rounded-xl border border-slate-200 bg-white p-2 shadow-xl"><Link onClick={()=>setExportOpen(false)} to="/reports?reportType=sales" className="block rounded-lg px-3 py-2 text-sm hover:bg-slate-50">{isAr?'تقرير المبيعات':'Sales report'}</Link><Link onClick={()=>setExportOpen(false)} to="/reports?reportType=sales_by_payment" className="block rounded-lg px-3 py-2 text-sm hover:bg-slate-50">{isAr?'طرق الدفع':'Payment methods'}</Link><Link onClick={()=>setExportOpen(false)} to="/reports?reportType=sales_by_branch" className="block rounded-lg px-3 py-2 text-sm hover:bg-slate-50">{isAr?'حسب الفرع':'By branch'}</Link></div>}</div></div></div></div>
  <div className="space-y-5 p-5"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric title={isAr?'الطلبات':'Orders'} value={formatNumber(metrics.orders,0)} hint={isAr?'إجمالي الطلبات':'Total orders'} icon={<ShoppingBag className="h-5 w-5"/>} tone="bg-[#5b2bd8]" href="/reports?reportType=detailed_invoices"/><Metric title={isAr?'إجمالي المبيعات':'Net Sales'} value={money(metrics.salesTotal)} hint={isAr?'مبيعات الفترة':'Period sales'} icon={<Wallet className="h-5 w-5"/>} tone="bg-[#16a34a]" href="/reports?reportType=sales"/><Metric title={isAr?'إجمالي المدفوعات':'Net Payments'} value={money(metrics.payments)} hint={isAr?'المبالغ المحصلة':'Collected payments'} icon={<CreditCard className="h-5 w-5"/>} tone="bg-[#2188e8]" href="/reports?reportType=sales_by_payment"/><Metric title={isAr?'المبالغ المرتجعة':'Return Amount'} value={money(metrics.returns)} hint={isAr?'مرتجعات الفترة':'Period returns'} icon={<RotateCcw className="h-5 w-5"/>} tone="bg-[#f59e0b]" href="/reports?reportType=sales"/><Metric title={isAr?'إجمالي الخصومات':'Discount Amount'} value={money(metrics.discounts)} hint={isAr?'خصومات الفترة':'Period discounts'} icon={<Tag className="h-5 w-5"/>} tone="bg-[#ec4899]" href="/reports?reportType=sales"/></div>
   <div className="grid grid-cols-1 gap-5 xl:grid-cols-[2fr_1fr]"><Card className="p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold">{isAr?'المبيعات':'Sales'}</h2><div className="mt-2 flex gap-5 text-xs text-slate-500"><span className="inline-flex items-center gap-2"><i className="h-2 w-6 rounded-full bg-brand-600"/>{isAr?'مبيعات اليوم':'Today sales'}</span><span className="inline-flex items-center gap-2"><i className="h-2 w-6 border-t-2 border-dashed border-brand-300"/>{isAr?'مبيعات سابقة':'Previous sales'}</span></div></div><select className="rounded-lg border border-slate-200 px-3 py-2 text-xs"><option>{isAr?'حسب الساعة':'By hour'}</option><option>{isAr?'حسب اليوم':'By day'}</option></select></div>{chart.length?<ResponsiveContainer width="100%" height={280}><AreaChart data={chart}><defs><linearGradient id="salesFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#5b2bd8" stopOpacity={0.24}/><stop offset="100%" stopColor="#5b2bd8" stopOpacity={0.02}/></linearGradient></defs><CartesianGrid strokeDasharray="4 4" vertical={false} stroke="#e5e7eb"/><XAxis dataKey="label" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:11}} axisLine={false} tickLine={false} tickFormatter={v=>`${Math.round(Number(v)/1000)}K`}/><Tooltip formatter={(v)=>money(Number(v))}/><Area type="monotone" dataKey="sales" stroke="#5b2bd8" strokeWidth={3} fill="url(#salesFill)"/></AreaChart></ResponsiveContainer>:<Empty ar={isAr}/>}</Card><Card className="p-5"><h2 className="font-bold">{isAr?'طرق الدفع':'Payment Methods'}</h2><div className="mt-3 flex items-center gap-5">{paymentMix.length?<><ResponsiveContainer width="52%" height={220}><PieChart><Pie data={paymentMix} dataKey="value" nameKey="name" innerRadius={62} outerRadius={88} paddingAngle={2}>{paymentMix.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={(v)=>money(Number(v))}/></PieChart></ResponsiveContainer><div className="min-w-0 flex-1 space-y-3">{paymentMix.map((p,i)=>{const label=paymentLabels[p.name]?.[isAr?0:1]||p.name;return <div key={p.name} className="text-xs"><div className="flex items-center justify-between gap-2"><span className="flex items-center gap-2 truncate"><i className="h-2.5 w-2.5 rounded-full" style={{background:colors[i%colors.length]}}/>{label}</span><b>{Math.round(p.value/Math.max(metrics.payments,1)*100)}%</b></div><div className="mt-1 h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full" style={{width:`${p.value/maxPayment*100}%`,background:colors[i%colors.length]}}/></div></div>})}</div></>:<Empty ar={isAr}/>}</div></Card></div>
   <div className="grid grid-cols-1 gap-5 xl:grid-cols-3"><Card className="p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">{isAr?'أعلى الفروع مبيعًا':'Top Selling Branches'}</h2><Link to="/reports?reportType=sales_by_branch" className="text-xs font-bold text-brand-600">{isAr?'عرض الكل':'View all'}</Link></div>{topBranches.length?topBranches.map((b,i)=><div key={b.name} className="mb-4"><div className="mb-1 flex justify-between text-sm"><span><b className="me-2 text-slate-400">{i+1}</b>{b.name}</span><b>{money(b.sales)}</b></div><div className="h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand-600" style={{width:`${b.sales/maxBranch*100}%`}}/></div><p className="mt-1 text-[11px] text-slate-400">{b.orders} {isAr?'طلب':'orders'}</p></div>):<Empty ar={isAr}/>}</Card><Card className="p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">{isAr?'أكثر الأصناف مبيعًا':'Top Selling Items'}</h2><Link to="/reports?reportType=sales_by_product" className="text-xs font-bold text-brand-600">{isAr?'عرض الكل':'View all'}</Link></div>{topProducts.length?topProducts.map((p,i)=><div key={p.name} className="flex items-center justify-between border-b border-slate-100 py-3 last:border-0"><div className="flex min-w-0 items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-slate-100 text-xs font-bold">{i+1}</span><span className="truncate text-sm font-medium">{p.name}</span></div><b className="text-sm">{formatNumber(p.quantity,0)}</b></div>):<Empty ar={isAr}/>}</Card><Card className="p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">{isAr?'أحدث الطلبات':'Recent Orders'}</h2><Link to="/reports?reportType=detailed_invoices" className="text-xs font-bold text-brand-600">{isAr?'عرض الكل':'View all'}</Link></div>{recent.length?recent.map((s,i)=>{const b=s.branch?.[0];return <div key={s.id} className="flex items-center justify-between border-b border-slate-100 py-3 last:border-0"><div className="flex min-w-0 items-center gap-3"><span className="text-xs text-slate-400">{i+1}</span><div className="min-w-0"><p className="text-sm font-semibold">#{s.invoice_number||'—'}</p><p className="truncate text-[11px] text-slate-400">{b?.name||'—'} · {s.order_type||'—'}</p></div></div><div className="text-end"><b className="text-sm">{money(Number(s.total||0))}</b><p className="text-[11px] text-emerald-600">{s.status||'completed'}</p></div></div>}) : <Empty ar={isAr}/>}</Card></div>
   {lowStock.length>0&&<Card className="border-amber-200 bg-amber-50/60 p-5"><div className="flex items-center gap-2 font-bold text-amber-800"><AlertTriangle className="h-5 w-5"/>{isAr?'تنبيه المخزون المنخفض':'Low Stock Alert'}</div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{lowStock.map((x,i)=><Link key={i} to="/inventory" className="rounded-xl bg-white p-3 shadow-sm"><p className="truncate text-sm font-semibold">{x.product?.[0]?.name||'—'}</p><p className="mt-1 text-xs text-amber-700">{formatNumber(Number(x.quantity||0),2)} {isAr?'متبقي':'remaining'}</p></Link>)}</div></Card>}
   <div className="flex items-center justify-between border-t border-slate-200 pt-5 text-xs text-slate-400"><span>Premier POS © 2026</span><span className="inline-flex items-center gap-2"><Building2 className="h-4 w-4"/>{isAr?'نظام إدارة المطاعم':'Restaurant Management System'}</span></div></div>
  {reportsOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" onClick={()=>setReportsOpen(false)}><div className="w-full max-w-2xl rounded-2xl bg-white p-6 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="text-xl font-bold">{isAr?'التقارير':'Reports'}</h2><button onClick={()=>setReportsOpen(false)} className="rounded-lg p-2 hover:bg-slate-100">×</button></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{reportItems.map(([ar,en,type])=><Link key={type} onClick={()=>setReportsOpen(false)} to={`/reports?reportType=${type}`} className="rounded-xl border border-slate-200 p-4 text-sm font-semibold hover:border-brand-300 hover:bg-brand-50">{isAr?ar:en}</Link>)}</div></div></div>}
 </div>}
