import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Activity, AlertTriangle, BarChart3, CalendarDays, CircleDollarSign, FileText, Package, RefreshCw, ShoppingBag, Sparkles, TrendingUp, Wallet } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { supabase } from '@/api';
import { useLanguage } from '@/context/LanguageContext';
import { useAuth } from '@/context/AuthContext';
import { useBranchFilter } from '@/lib/useBranchFilter';
import { isAdminRole } from '@/lib/permissions';
import { useBranches } from '@/hooks/useBranches';
import { useSettings } from '@/context/SettingsContext';
import { formatCurrency, formatDateTime, formatNumber } from '@/lib/format';

type Range = 'today' | 'week' | 'month' | 'year';
type Data = { sales:number; expenses:number; profit:number; invoices:number; lowStock:number; products:number; trend:{label:string;total:number}[]; top:{name:string;total:number}[]; recent:any[] };

const ranges: Record<Range,[string,string]> = { today:['اليوم','Today'], week:['7 أيام','7 Days'], month:['30 يوم','30 Days'], year:['سنة','Year'] };

function Card({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={`rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-navy-800 dark:bg-navy-900 ${className}`}>{children}</section>}
function Metric({title,value,icon,tone,hint}:{title:string;value:string;icon:React.ReactNode;tone:string;hint:string}){return <Card className="relative overflow-hidden p-5 transition hover:-translate-y-0.5 hover:shadow-md"><div className={`absolute inset-x-0 top-0 h-1 ${tone}`}/><div className={`flex h-11 w-11 items-center justify-center rounded-xl ${tone} text-white`}>{icon}</div><p className="mt-4 text-sm font-medium text-slate-500 dark:text-slate-400">{title}</p><p className="mt-1 text-2xl font-bold text-slate-900 dark:text-white">{value}</p><p className="mt-1 text-xs text-slate-400">{hint}</p></Card>}

export function DashboardFinalPage(){
 const {lang}=useLanguage(); const {user}=useAuth(); const {branches}=useBranches(); const branchFilter=useBranchFilter(); const {effectiveSettings}=useSettings();
 const isAr=lang==='ar'; const [range,setRange]=useState<Range>('today'); const [branchId,setBranchId]=useState(''); const [data,setData]=useState<Data|null>(null); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false);
 const effectiveBranch=isAdminRole(user?.role)?(branchId||null):branchFilter; const currency=effectiveSettings(effectiveBranch)?.currency||'EGP';
 const load=useCallback(async()=>{setRefreshing(true); try{
   const end=new Date(); const start=new Date(end); if(range==='today')start.setHours(0,0,0,0); if(range==='week')start.setDate(start.getDate()-6); if(range==='month')start.setDate(start.getDate()-29); if(range==='year')start.setFullYear(start.getFullYear()-1);
   const from=start.toISOString(),to=end.toISOString(); const branch=(q:any)=>effectiveBranch?q.eq('branch_id',effectiveBranch):q;
   const [salesR,expR,prodR,invR,itemR]=await Promise.all([
    branch(supabase.from('sales').select('id,invoice_number,total,created_at').gte('created_at',from).lte('created_at',to).order('created_at',{ascending:false})),
    branch(supabase.from('expenses').select('amount,expense_date').gte('expense_date',from.slice(0,10)).lte('expense_date',to.slice(0,10))),
    supabase.from('products').select('id',{count:'exact',head:true}),
    supabase.from('inventory').select('quantity,product:products(name,low_stock_threshold)'),
    supabase.from('sale_items').select('quantity,total,product:products(name)').limit(1000)
   ]);
   const salesRows:any[]=salesR.data||[], expRows:any[]=expR.data||[]; const sales=salesRows.reduce((n,r)=>n+Number(r.total||0),0); const expenses=expRows.reduce((n,r)=>n+Number(r.amount||0),0); const threshold=Number(effectiveSettings(effectiveBranch)?.low_stock_threshold??5);
   const lowStock=(invR.data||[]).filter((r:any)=>Number(r.quantity||0)<Number(r.product?.low_stock_threshold??threshold)).length;
   const topMap=new Map<string,number>(); (itemR.data||[]).forEach((r:any)=>{const n=r.product?.name||'-';topMap.set(n,(topMap.get(n)||0)+Number(r.total||0))});
   const map=new Map<string,number>(); salesRows.forEach(r=>{const d=new Date(r.created_at);const k=range==='year'?`${d.getFullYear()}-${d.getMonth()+1}`:d.toISOString().slice(0,10);map.set(k,(map.get(k)||0)+Number(r.total||0))});
   const trend=Array.from(map.entries()).map(([k,total])=>({label:range==='year'?k.split('-')[1]:new Date(k).toLocaleDateString(isAr?'ar-EG':'en-US',{day:'numeric',month:'short'}),total}));
   setData({sales,expenses,profit:sales-expenses,invoices:salesRows.length,lowStock,products:prodR.count||0,trend,top:Array.from(topMap.entries()).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([name,total])=>({name,total})),recent:salesRows.slice(0,6)});
 } finally{setLoading(false);setRefreshing(false)}},[range,effectiveBranch,effectiveSettings,isAr]);
 useEffect(()=>{void load()},[load]);
 if(loading||!data)return <div className="flex min-h-[60vh] items-center justify-center"><RefreshCw className="h-8 w-8 animate-spin text-brand-600"/></div>;
 const margin=data.sales?data.profit/data.sales*100:0; const greeting=new Date().getHours()<12?(isAr?'صباح الخير':'Good morning'):(isAr?'مساء الخير':'Good evening');
 return <div className="space-y-6 pb-8">
  <div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-navy-950 via-navy-900 to-slate-900 p-6 shadow-xl sm:p-8"><div className="absolute -right-16 -top-16 h-64 w-64 rounded-full bg-gold-500/10 blur-3xl"/><div className="relative flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-2 flex items-center gap-2 text-sm text-gold-300"><Sparkles className="h-4 w-4"/>{greeting}</div><h1 className="text-3xl font-bold text-white">{user?.full_name||(isAr?'لوحة التحكم':'Dashboard')}</h1><p className="mt-1 text-sm text-slate-400">{new Date().toLocaleDateString(isAr?'ar-EG':'en-US',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p></div><div className="flex items-center gap-3"><div className="rounded-2xl border border-white/10 bg-white/5 px-5 py-3"><p className="text-xs text-slate-400">{isAr?'ربح الفترة':'Period profit'}</p><p className="text-xl font-bold text-white">{formatCurrency(data.profit,currency,lang)}</p></div><Link to="/pos" className="inline-flex items-center gap-2 rounded-2xl bg-gold-500 px-5 py-3 text-sm font-bold text-navy-950 hover:bg-gold-400"><ShoppingBag className="h-4 w-4"/>{isAr?'بيع جديد':'New Sale'}</Link></div></div></div>
  <Card className="p-4"><div className="flex flex-wrap items-center gap-2"><CalendarDays className="h-4 w-4 text-brand-600"/>{(Object.keys(ranges) as Range[]).map(r=><button key={r} onClick={()=>setRange(r)} className={`rounded-xl px-4 py-2 text-sm font-semibold ${range===r?'bg-navy-900 text-white dark:bg-brand-600':'bg-slate-100 text-slate-600 dark:bg-navy-800 dark:text-slate-300'}`}>{ranges[r][isAr?0:1]}</button>)}{isAdminRole(user?.role)&&branches.length>0&&<select value={branchId} onChange={e=>setBranchId(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-navy-700 dark:bg-navy-800 dark:text-slate-200"><option value="">{isAr?'كل الفروع':'All branches'}</option>{branches.map(b=><option key={b.id} value={b.id}>{isAr?b.name:b.name_en||b.name}</option>)}</select>}<button onClick={()=>void load()} className="ml-auto inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm dark:border-navy-700 dark:text-slate-300"><RefreshCw className={`h-4 w-4 ${refreshing?'animate-spin':''}`}/>{isAr?'تحديث':'Refresh'}</button></div></Card>
  <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric title={isAr?'المبيعات':'Sales'} value={formatCurrency(data.sales,currency,lang)} icon={<CircleDollarSign className="h-5 w-5"/>} tone="bg-gradient-to-br from-navy-800 to-navy-950" hint={`${data.invoices} ${isAr?'فاتورة':'invoices'}`}/><Metric title={isAr?'المصروفات':'Expenses'} value={formatCurrency(data.expenses,currency,lang)} icon={<FileText className="h-5 w-5"/>} tone="bg-gradient-to-br from-rose-500 to-rose-600" hint={isAr?'خلال الفترة':'Selected period'}/><Metric title={isAr?'صافي الربح':'Net profit'} value={formatCurrency(data.profit,currency,lang)} icon={<Wallet className="h-5 w-5"/>} tone="bg-gradient-to-br from-gold-400 to-gold-600" hint={`${margin.toFixed(1)}% ${isAr?'هامش':'margin'}`}/><Metric title={isAr?'الفواتير':'Invoices'} value={formatNumber(data.invoices,0)} icon={<BarChart3 className="h-5 w-5"/>} tone="bg-gradient-to-br from-brand-500 to-brand-600" hint={isAr?'طلبات مكتملة':'Completed sales'}/><Metric title={isAr?'مخزون منخفض':'Low stock'} value={formatNumber(data.lowStock,0)} icon={<AlertTriangle className="h-5 w-5"/>} tone="bg-gradient-to-br from-amber-500 to-orange-500" hint={data.lowStock?(isAr?'يحتاج إعادة طلب':'Needs restock'):(isAr?'المخزون جيد':'Stock healthy')}/></div>
  <div className="grid grid-cols-1 gap-6 xl:grid-cols-3"><Card className="p-5 xl:col-span-2"><div className="mb-4 flex items-center gap-2"><Activity className="h-4 w-4 text-brand-600"/><div><h2 className="font-bold text-slate-800 dark:text-white">{isAr?'اتجاه المبيعات':'Sales trend'}</h2><p className="text-xs text-slate-400">{isAr?'حركة المبيعات خلال الفترة':'Sales movement'}</p></div></div><ResponsiveContainer width="100%" height={300}><AreaChart data={data.trend}><defs><linearGradient id="dashFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#D4AF37" stopOpacity={0.35}/><stop offset="100%" stopColor="#D4AF37" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:11}} axisLine={false} tickLine={false}/><Tooltip formatter={(v:any)=>formatCurrency(Number(v),currency,lang)}/><Area type="monotone" dataKey="total" stroke="#D4AF37" strokeWidth={3} fill="url(#dashFill)"/></AreaChart></ResponsiveContainer></Card><Card className="p-5"><div className="mb-4 flex items-center gap-2"><TrendingUp className="h-4 w-4 text-emerald-500"/><h2 className="font-bold text-slate-800 dark:text-white">{isAr?'أفضل المنتجات':'Top products'}</h2></div>{data.top.length?<ResponsiveContainer width="100%" height={300}><BarChart data={data.top} layout="vertical"><CartesianGrid horizontal={false}/><XAxis type="number" hide/><YAxis type="category" dataKey="name" width={90} tick={{fontSize:10}} axisLine={false} tickLine={false}/><Tooltip formatter={(v:any)=>formatCurrency(Number(v),currency,lang)}/><Bar dataKey="total" fill="#0F172A" radius={[0,6,6,0]} barSize={18}/></BarChart></ResponsiveContainer>:<p className="py-20 text-center text-sm text-slate-400">{isAr?'لا توجد بيانات':'No data'}</p>}</Card></div>
  <div className="grid grid-cols-1 gap-6 lg:grid-cols-3"><Card className="p-5 lg:col-span-2"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold text-slate-800 dark:text-white">{isAr?'آخر المبيعات':'Recent sales'}</h2><p className="text-xs text-slate-400">{isAr?'أحدث الفواتير':'Latest invoices'}</p></div><Link to="/sales" className="text-xs font-semibold text-brand-600">{isAr?'عرض الكل':'View all'}</Link></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-slate-100 dark:border-navy-800"><th className="py-3 text-start text-xs text-slate-400">{isAr?'الفاتورة':'Invoice'}</th><th className="py-3 text-start text-xs text-slate-400">{isAr?'التاريخ':'Date'}</th><th className="py-3 text-end text-xs text-slate-400">{isAr?'الإجمالي':'Total'}</th></tr></thead><tbody>{data.recent.map(s=><tr key={s.id} className="border-b border-slate-50 dark:border-navy-800"><td className="py-3 font-semibold text-slate-700 dark:text-white">{s.invoice_number||'-'}</td><td className="py-3 text-slate-400">{formatDateTime(s.created_at,lang)}</td><td className="py-3 text-end font-bold text-brand-600 dark:text-gold-400">{formatCurrency(Number(s.total),currency,lang)}</td></tr>)}{!data.recent.length&&<tr><td colSpan={3} className="py-10 text-center text-slate-400">{isAr?'لا توجد مبيعات':'No sales'}</td></tr>}</tbody></table></div></Card><Card className="p-5"><div className="flex items-center gap-2"><Package className="h-4 w-4 text-amber-500"/><h2 className="font-bold text-slate-800 dark:text-white">{isAr?'حالة المخزون':'Inventory status'}</h2></div><div className={`mt-5 rounded-2xl p-4 ${data.lowStock?'bg-amber-50 dark:bg-amber-900/10':'bg-emerald-50 dark:bg-emerald-900/10'}`}><p className="font-semibold text-slate-700 dark:text-slate-200">{data.lowStock?(isAr?'تحتاج مراجعة':'Needs attention'):(isAr?'المخزون مستقر':'Stock is stable')}</p><p className="mt-1 text-xs text-slate-400">{data.lowStock?`${data.lowStock} ${isAr?'أصناف منخفضة':'low-stock items'}`:(isAr?'لا توجد تنبيهات':'No alerts')}</p></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3 dark:bg-navy-800"><p className="text-xs text-slate-400">{isAr?'المنتجات':'Products'}</p><p className="text-lg font-bold dark:text-white">{formatNumber(data.products,0)}</p></div><div className="rounded-xl bg-slate-50 p-3 dark:bg-navy-800"><p className="text-xs text-slate-400">{isAr?'الهامش':'Margin'}</p><p className="text-lg font-bold dark:text-white">{margin.toFixed(1)}%</p></div></div><Link to="/inventory" className="mt-5 inline-flex text-sm font-semibold text-brand-600">{isAr?'إدارة المخزون':'Manage inventory'} →</Link></Card></div>
 </div>
}