/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'Cairo', 'system-ui', 'sans-serif'],
        arabic: ['Cairo', 'Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        navy: {
          50: 'rgb(var(--navy-50) / <alpha-value>)',
          100: 'rgb(var(--navy-100) / <alpha-value>)',
          200: 'rgb(var(--navy-200) / <alpha-value>)',
          300: 'rgb(var(--navy-300) / <alpha-value>)',
          400: 'rgb(var(--navy-400) / <alpha-value>)',
          500: 'rgb(var(--navy-500) / <alpha-value>)',
          600: 'rgb(var(--navy-600) / <alpha-value>)',
          700: 'rgb(var(--navy-700) / <alpha-value>)',
          800: 'rgb(var(--navy-800) / <alpha-value>)',
          900: 'rgb(var(--navy-900) / <alpha-value>)',
          950: 'rgb(var(--navy-950) / <alpha-value>)',
        },
        gold: {
          50: '#fbf8ef',
          100: '#f5eed8',
          200: '#eadcaf',
          300: '#dfc887',
          400: '#d9bc62',
          500: '#D4AF37',
          600: '#b7952a',
          700: '#927422',
          800: '#735b1f',
          900: '#5c4a1e',
        },
        brand: {
          50: 'rgb(var(--brand-50) / <alpha-value>)',
          100: 'rgb(var(--brand-100) / <alpha-value>)',
          200: 'rgb(var(--brand-200) / <alpha-value>)',
          300: 'rgb(var(--brand-300) / <alpha-value>)',
          400: 'rgb(var(--brand-400) / <alpha-value>)',
          500: 'rgb(var(--brand-500) / <alpha-value>)',
          600: 'rgb(var(--brand-600) / <alpha-value>)',
          700: 'rgb(var(--brand-700) / <alpha-value>)',
          800: 'rgb(var(--brand-800) / <alpha-value>)',
          900: 'rgb(var(--brand-900) / <alpha-value>)',
        },
        ui: {
          primary: 'rgb(var(--ui-primary) / <alpha-value>)',
          'primary-hover': 'rgb(var(--ui-primary-hover) / <alpha-value>)',
          'primary-active': 'rgb(var(--ui-primary-active) / <alpha-value>)',
          'primary-soft': 'rgb(var(--ui-primary-soft) / <alpha-value>)',
          'primary-fg': 'rgb(var(--ui-primary-fg) / <alpha-value>)',
          accent: 'rgb(var(--ui-accent) / <alpha-value>)',
          surface: 'rgb(var(--ui-surface) / <alpha-value>)',
          'surface-raised': 'rgb(var(--ui-surface-raised) / <alpha-value>)',
          page: 'rgb(var(--ui-page) / <alpha-value>)',
          'page-alt': 'rgb(var(--ui-page-alt) / <alpha-value>)',
          border: 'rgb(var(--ui-border) / <alpha-value>)',
          'border-strong': 'rgb(var(--ui-border-strong) / <alpha-value>)',
          text: 'rgb(var(--ui-text) / <alpha-value>)',
          muted: 'rgb(var(--ui-muted) / <alpha-value>)',
          subtle: 'rgb(var(--ui-subtle) / <alpha-value>)',
          success: 'rgb(var(--ui-success) / <alpha-value>)',
          warning: 'rgb(var(--ui-warning) / <alpha-value>)',
          danger: 'rgb(var(--ui-danger) / <alpha-value>)',
          info: 'rgb(var(--ui-info) / <alpha-value>)',
          ring: 'rgb(var(--ui-ring) / <alpha-value>)',
        },
      },
      boxShadow: {
        'soft': '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)',
        'soft-lg': '0 10px 40px -10px rgba(0, 0, 0, 0.1)',
        'card': '0 0 0 1px rgba(0,0,0,.03), 0 2px 4px rgba(0,0,0,.05)',
        'card-hover': '0 8px 25px -5px rgba(0,0,0,.1), 0 0 0 1px rgba(0,0,0,.03)',
        'pos': '0 4px 30px rgba(0, 0, 0, 0.15)',
        'ui-sm': 'var(--ui-shadow-sm)',
        'ui': 'var(--ui-shadow)',
        'ui-md': 'var(--ui-shadow-md)',
        'ui-lg': 'var(--ui-shadow-lg)',
        'ui-xl': 'var(--ui-shadow-xl)',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.2s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'ripple': 'ripple 0.6s linear',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        ripple: {
          '0%': { transform: 'scale(0)', opacity: '0.5' },
          '100%': { transform: 'scale(4)', opacity: '0' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
      },
      borderRadius: {
        '2xl': '1rem',
        '3xl': '1.5rem',
        'ui-sm': 'var(--ui-radius-sm)',
        'ui': 'var(--ui-radius)',
        'ui-lg': 'var(--ui-radius-lg)',
        'ui-xl': 'var(--ui-radius-xl)',
        'ui-2xl': 'var(--ui-radius-2xl)',
      },
    },
  },
  plugins: [],
};
