import { useEffect, useState } from 'react';
import { Grid3x3, ChefHat, ListOrdered, Plus, Wifi, WifiOff, Timer, Moon, Sun, LogOut, Tag, Zap, Clock3, MoreHorizontal } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useLanguage } from '@/context/LanguageContext';
import { useTheme } from '@/context/ThemeContext';
import { useAuth } from '@/context/AuthContext';
import { Logo } from '@/components/Logo';
import type { Branch } from '@/lib/types';
import type { ActiveShiftInfo } from '../../hooks/usePosOrder';
export type PosPanelId = 'orders' | 'tables' | 'kitchen' | null;
interface PosTopBarProps { panel: PosPanelId; onPanel:(p:Exclude<PosPanelId,null>)=>void; counts:{activeOrders:number;occupiedTables:number;kitchenOrders:number;heldOrders:number;deliveryOrders:number;takeawayOrders:number}; branchId:string; branches:Branch[]; canChangeBranch:boolean; onBranchChange:(id:string)=>void; isCashier:boolean; shiftChecked:boolean; activeShift:ActiveShiftInfo|null; onNewOrder:()=>void; onExit:()=>void; }
export function PosTopBar({panel,onPanel,counts,branchId,branches,canChangeBranch,onBranchChange,isCashier,shiftChecked,activeShift,onNewOrder,onExit}:PosTopBarProps){
 const {t,lang}=useLanguage(); const {theme,toggleTheme}=useTheme(); const {user,signOut}=useAuth(); const navigate=useNavigate(); const isAr=lang==='ar';
 const [now,setNow]=useState(()=>new Date()); const [online,setOnline]=useState(typeof navigator!=='undefined'?navigator.onLine:true); const [more,setMore]=useState(false);
 useEffect(()=>{const id=setInterval(()=>setNow(new Date()),30000);const on=()=>setOnline(true),off=()=>setOnline(false);window.addEventListener('online',on);window.addEventListener('offline',off);return()=>{clearInterval(id);window.removeEventListener('online',on);window.removeEventListener('offline',off)}},[]);
 const nav=(id:Exclude<PosPanelId,null>,icon:React.ReactNode,label:string,badge:number,tone:string)=><button onClick={()=>{onPanel(id);setMore(false)}} aria-pressed={panel===id} className={`relative flex min-h-11 items-center gap-2 rounded-xl border px-3.5 text-xs font-black transition active:scale-95 ${panel===id?`${tone} border-transparent shadow-md`:'border-slate-200 bg-white text-slate-600 hover:border-slate-300 dark:border-navy-700 dark:bg-navy-800 dark:text-slate-300'}`}>{icon}<span className="hidden md:inline">{label}</span>{badge>0&&<span className={`min-w-5 rounded-full px-1 text-[10px] ${panel===id?'bg-white/20 text-white':'bg-navy-950 text-white dark:bg-gold-500 dark:text-navy-950'}`}>{badge}</span>}</button>;
 return <header className="sticky top-0 z-50 flex min-h-[68px] items-center gap-2 border-b border-slate-200/80 bg-white/95 px-3 shadow-sm backdrop-blur dark:border-navy-800 dark:bg-navy-900/95 md:px-4">
   <div className="flex shrink-0 items-center gap-2"><Logo variant="mark" size={38} tone="auto"/><div className="hidden leading-tight sm:block"><p className="text-[15px] font-black text-slate-950 dark:text-white">Premier</p><p className="text-[9px] font-black uppercase tracking-[.18em] text-gold-600 dark:text-gold-400">{t('pos')}</p></div><button onClick={onNewOrder} className="ms-1 flex min-h-11 items-center gap-2 rounded-xl bg-navy-950 px-3.5 text-xs font-black text-white shadow-lg transition active:scale-95 hover:bg-navy-800 dark:bg-gold-500 dark:text-navy-950"><Plus className="h-4 w-4"/><span className="hidden sm:inline">{t('newOrder')}</span></button></div>
   <div className="hidden h-9 w-px bg-slate-200 dark:bg-navy-700 sm:block"/>
   <nav className="flex min-w-0 gap-1.5 overflow-x-auto scrollbar-none">{nav('orders',<ListOrdered className="h-4 w-4"/>,t('activeOrders'),counts.activeOrders,'bg-brand-600 text-white')}{nav('tables',<Grid3x3 className="h-4 w-4"/>,t('tables'),counts.occupiedTables,'bg-emerald-600 text-white')}{nav('kitchen',<ChefHat className="h-4 w-4"/>,t('kitchen'),counts.kitchenOrders,'bg-orange-600 text-white')}</nav>
   <div className="flex-1"/>
   <div className={`hidden items-center gap-2 rounded-xl border px-3 py-2 text-[11px] font-black xl:flex ${online?'border-emerald-100 bg-emerald-50 text-emerald-700 dark:border-emerald-800 dark:bg-emerald-900/20 dark:text-emerald-300':'border-red-100 bg-red-50 text-red-700 dark:border-red-800 dark:bg-red-900/20 dark:text-red-300'}`}>{online?<Wifi className="h-3.5 w-3.5"/>:<WifiOff className="h-3.5 w-3.5"/>}{online?t('online'):t('offline')}</div>
   <div className="hidden items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-bold text-slate-600 lg:flex dark:border-navy-700 dark:bg-navy-800 dark:text-slate-200"><Clock3 className="h-3.5 w-3.5 text-slate-400"/>{now.toLocaleTimeString(isAr?'ar-EG':'en-US',{hour:'2-digit',minute:'2-digit'})}</div>
   {isCashier&&shiftChecked&&<button onClick={()=>navigate('/shifts')} className={`hidden min-h-10 items-center gap-2 rounded-xl border px-3 text-[11px] font-black md:flex ${activeShift?'border-emerald-100 bg-emerald-50 text-emerald-700':'border-amber-100 bg-amber-50 text-amber-700'}`}><Timer className="h-3.5 w-3.5"/>{activeShift?t('open'):t('noOpenShift')}</button>}
   <div className="relative"><button onClick={()=>setMore(v=>!v)} className="flex min-h-11 items-center justify-center rounded-xl border border-slate-200 bg-white px-3 text-slate-500 dark:border-navy-700 dark:bg-navy-800 dark:text-slate-300"><MoreHorizontal className="h-5 w-5"/></button>{more&&<div className="absolute end-0 top-13 z-50 w-64 rounded-2xl border border-slate-200 bg-white p-2 shadow-2xl dark:border-navy-700 dark:bg-navy-900"><div className="mb-1 px-3 py-2 text-xs font-black text-slate-400">{isAr?'إجراءات سريعة':'Quick actions'}</div><button onClick={()=>{navigate('/shifts');setMore(false)}} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold hover:bg-slate-50 dark:hover:bg-navy-800"><Timer className="h-4 w-4"/>{isAr?'الوردية':'Shift'}</button><div className="my-1 h-px bg-slate-100 dark:bg-navy-800"/><div className="px-3 py-2 text-[11px] text-slate-400">{isAr?'الفرع':'Branch'}</div><select value={branchId} disabled={!canChangeBranch} onChange={e=>{onBranchChange(e.target.value);setMore(false)}} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm font-bold dark:border-navy-700 dark:bg-navy-800 dark:text-white"><option value="">{isAr?'اختر الفرع':'Select Branch'}</option>{branches.map(b=><option key={b.id} value={b.id}>{isAr?b.name:(b.name_en||b.name)}</option>)}</select></div>}</div>
   <div className="hidden items-center gap-2 lg:flex"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-navy-950 text-xs font-black text-white ring-1 ring-gold-500/40 dark:bg-navy-700">{(user?.full_name||user?.email||'?')[0].toUpperCase()}</div><div className="max-w-[120px] leading-tight"><p className="truncate text-xs font-black text-slate-800 dark:text-white">{user?.full_name||user?.email}</p><p className="flex items-center gap-1 text-[10px] text-slate-400"><Zap className="h-2.5 w-2.5 text-gold-500"/>{user?.role}</p></div></div>
   <button onClick={toggleTheme} className="flex min-h-11 min-w-11 items-center justify-center rounded-xl text-slate-500 hover:bg-slate-100 dark:hover:bg-navy-800">{theme==='light'?<Moon className="h-4 w-4"/>:<Sun className="h-4 w-4"/>}</button><button onClick={onExit} className="hidden min-h-11 min-w-11 items-center justify-center rounded-xl text-slate-500 hover:bg-slate-100 dark:hover:bg-navy-800 sm:flex"><LogOut className="h-4 w-4 rotate-180"/></button><button onClick={()=>void signOut()} className="flex min-h-11 min-w-11 items-center justify-center rounded-xl text-slate-400 hover:bg-red-50 hover:text-red-600"><LogOut className="h-4 w-4"/></button>
 </header>;
}