import { useEffect, useMemo, useState } from 'react';
import { Activity, BarChart3, Bell, Boxes, Calculator, Check, ChevronDown, FileText, Globe2, LayoutDashboard, Package, Palette, Printer, Receipt, Save, ShieldCheck, ShoppingCart, SlidersHorizontal, Store, Users, Wrench, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { supabase } from '@/api';
import { Card } from '@/components/PageHeader';
import { Button } from '@/components/Button';
import { useLanguage } from '@/context/LanguageContext';
import { useToast } from '@/components/Toast';

type Config = Record<string, Record<string, string | number | boolean>>;
type Field = { key: string; label: string; type: 'toggle' | 'number' | 'text' | 'select'; options?: [string, string][]; help?: string };
type Section = { key: string; ar: string; en: string; icon: React.ReactNode; fields: Field[] };

const DEFAULT_CONFIG: Config = {
  general:{default_language:'ar',default_currency:'EGP',date_format:'DD/MM/YYYY',time_format:'24h',week_starts:'saturday'},
  pos:{default_order_type:'quick',ask_table_people:true,allow_hold:true,allow_split:true,allow_discount:true,allow_price_override:false,require_customer:false,auto_print:false,auto_close_order:false,show_product_images:true},
  order_types:{dine_in:true,delivery:true,takeaway:true,quick:true,car:true},
  payments:{cash:true,card:true,wallet:true,credit:false,other:false,default_method:'cash'},
  sales:{tax_enabled:false,tax_rate:0,discount_max_percent:100,allow_returns:true,return_requires_approval:false,negative_stock:false,invoice_prefix:'INV-'},
  inventory:{low_stock_threshold:5,allow_negative:false,auto_deduct_on_sale:true,auto_deduct_components:true,allow_zero_cost:false,enable_expiry:false},
  purchases:{auto_post_inventory:true,require_receiving:false,allow_edit_posted:false,default_payment_status:'unpaid'},
  manufacturing:{auto_consume_components:true,allow_overproduction:false,require_approval:false,rounding_decimals:3},
  accounting:{auto_journal:true,fiscal_year_start:'01-01',decimal_places:2,cost_method:'weighted_average'},
  customers_suppliers:{allow_customer_credit:false,allow_supplier_credit:true,credit_limit_default:0,require_phone:false},
  printing:{paper:'80mm',copies:1,show_logo:true,show_tax:true,show_cashier:true,show_customer:true,show_barcode:true,footer:'شكراً لزيارتكم'},
  dashboard:{default_range:'today',show_sales:true,show_expenses:true,show_profit:true,show_inventory:true,show_top_products:true,show_recent_sales:true,show_payment_chart:true,show_employee_chart:true},
  reports:{default_range:'today',default_rows:25,show_zero_rows:false,allow_export_excel:true,allow_export_pdf:true,allow_print:true},
  notifications:{low_stock:true,shift_open:true,shift_close:true,purchase_due:true,customer_due:false},
  security:{session_timeout_minutes:480,max_login_attempts:5,lockout_minutes:15,require_password_change:false,audit_all_changes:true},
  ui:{compact_tables:false,animations:true,confirm_delete:true,confirm_post:true,rtl:true,show_help:true},
};

const sections: Section[] = [
 {key:'general',ar:'الإعدادات العامة',en:'General',icon:<Store className="h-5 w-5"/>,fields:[
  {key:'default_language',label:'اللغة الافتراضية',type:'select',options:[['ar','العربية'],['en','English']]},{key:'default_currency',label:'العملة الافتراضية',type:'text'},{key:'date_format',label:'تنسيق التاريخ',type:'select',options:[['DD/MM/YYYY','31/12/2026'],['MM/DD/YYYY','12/31/2026'],['YYYY-MM-DD','2026-12-31']]},{key:'time_format',label:'تنسيق الوقت',type:'select',options:[['24h','24 ساعة'],['12h','12 ساعة']]},{key:'week_starts',label:'بداية الأسبوع',type:'select',options:[['saturday','السبت'],['sunday','الأحد'],['monday','الإثنين']]}]},
 {key:'pos',ar:'نقطة البيع POS',en:'POS',icon:<ShoppingCart className="h-5 w-5"/>,fields:[
  {key:'default_order_type',label:'نوع الطلب الافتراضي',type:'select',options:[['quick','طلب سريع'],['dine_in','صالة'],['delivery','دليفري'],['takeaway','تيك أواي'],['car','سيارة']]},{key:'ask_table_people',label:'طلب عدد أفراد الطاولة',type:'toggle'},{key:'allow_hold',label:'السماح بتعليق الطلب',type:'toggle'},{key:'allow_split',label:'السماح بتقسيم الفاتورة',type:'toggle'},{key:'allow_discount',label:'السماح بالخصم',type:'toggle'},{key:'allow_price_override',label:'السماح بتعديل السعر',type:'toggle'},{key:'require_customer',label:'إلزام اختيار العميل',type:'toggle'},{key:'auto_print',label:'طباعة تلقائية بعد البيع',type:'toggle'},{key:'auto_close_order',label:'إغلاق الطلب تلقائياً',type:'toggle'},{key:'show_product_images',label:'عرض صور المنتجات',type:'toggle'}]},
 {key:'order_types',ar:'أنواع الطلبات',en:'Order Types',icon:<Receipt className="h-5 w-5"/>,fields:[{key:'dine_in',label:'صالة / طاولة',type:'toggle'},{key:'delivery',label:'دليفري',type:'toggle'},{key:'takeaway',label:'تيك أواي',type:'toggle'},{key:'quick',label:'طلب سريع',type:'toggle'},{key:'car',label:'سيارة',type:'toggle'}]},
 {key:'payments',ar:'طرق الدفع',en:'Payments',icon:<Calculator className="h-5 w-5"/>,fields:[{key:'cash',label:'نقدي',type:'toggle'},{key:'card',label:'بطاقة',type:'toggle'},{key:'wallet',label:'محفظة إلكترونية',type:'toggle'},{key:'credit',label:'آجل',type:'toggle'},{key:'other',label:'أخرى',type:'toggle'},{key:'default_method',label:'طريقة الدفع الافتراضية',type:'select',options:[['cash','نقدي'],['card','بطاقة'],['wallet','محفظة'],['credit','آجل']]}]},
 {key:'sales',ar:'المبيعات والخصومات والمرتجعات',en:'Sales',icon:<Activity className="h-5 w-5"/>,fields:[{key:'tax_enabled',label:'تفعيل الضريبة',type:'toggle'},{key:'tax_rate',label:'نسبة الضريبة %',type:'number'},{key:'discount_max_percent',label:'أقصى خصم %',type:'number'},{key:'allow_returns',label:'السماح بالمرتجعات',type:'toggle'},{key:'return_requires_approval',label:'المرتجع يحتاج اعتماد',type:'toggle'},{key:'negative_stock',label:'السماح بالبيع بالسالب',type:'toggle'},{key:'invoice_prefix',label:'بادئة رقم الفاتورة',type:'text'}]},
 {key:'inventory',ar:'المخزون والمستودعات',en:'Inventory',icon:<Boxes className="h-5 w-5"/>,fields:[{key:'low_stock_threshold',label:'حد المخزون المنخفض',type:'number'},{key:'allow_negative',label:'السماح بالمخزون السالب',type:'toggle'},{key:'auto_deduct_on_sale',label:'خصم المخزون تلقائياً عند البيع',type:'toggle'},{key:'auto_deduct_components',label:'خصم المكونات تلقائياً',type:'toggle'},{key:'allow_zero_cost',label:'السماح بتكلفة صفرية',type:'toggle'},{key:'enable_expiry',label:'تفعيل تواريخ الصلاحية',type:'toggle'}]},
 {key:'purchases',ar:'المشتريات',en:'Purchases',icon:<Package className="h-5 w-5"/>,fields:[{key:'auto_post_inventory',label:'إضافة للمخزون تلقائياً',type:'toggle'},{key:'require_receiving',label:'اشتراط استلام المشتريات',type:'toggle'},{key:'allow_edit_posted',label:'السماح بتعديل المستند المرحّل',type:'toggle'},{key:'default_payment_status',label:'حالة الدفع الافتراضية',type:'select',options:[['unpaid','غير مدفوع'],['partial','مدفوع جزئياً'],['paid','مدفوع']]}]},
 {key:'manufacturing',ar:'التصنيع والوصفات',en:'Manufacturing',icon:<Wrench className="h-5 w-5"/>,fields:[{key:'auto_consume_components',label:'استهلاك المكونات تلقائياً',type:'toggle'},{key:'allow_overproduction',label:'السماح بالإنتاج الزائد',type:'toggle'},{key:'require_approval',label:'طلب الإنتاج يحتاج اعتماد',type:'toggle'},{key:'rounding_decimals',label:'عدد الخانات العشرية للكميات',type:'number'}]},
 {key:'accounting',ar:'المحاسبة والتكلفة',en:'Accounting',icon:<Calculator className="h-5 w-5"/>,fields:[{key:'auto_journal',label:'إنشاء القيود تلقائياً',type:'toggle'},{key:'fiscal_year_start',label:'بداية السنة المالية',type:'text'},{key:'decimal_places',label:'الخانات العشرية',type:'number'},{key:'cost_method',label:'طريقة احتساب التكلفة',type:'select',options:[['weighted_average','متوسط مرجح'],['fifo','FIFO']]}]},
 {key:'customers_suppliers',ar:'العملاء والموردون',en:'Customers & Suppliers',icon:<Users className="h-5 w-5"/>,fields:[{key:'allow_customer_credit',label:'السماح بآجل للعملاء',type:'toggle'},{key:'allow_supplier_credit',label:'السماح بآجل للموردين',type:'toggle'},{key:'credit_limit_default',label:'حد الائتمان الافتراضي',type:'number'},{key:'require_phone',label:'إلزام رقم الهاتف',type:'toggle'}]},
 {key:'printing',ar:'الطباعة والإيصالات',en:'Printing',icon:<Printer className="h-5 w-5"/>,fields:[{key:'paper',label:'مقاس الورق',type:'select',options:[['58mm','58mm'],['80mm','80mm'],['A4','A4']]},{key:'copies',label:'عدد النسخ',type:'number'},{key:'show_logo',label:'إظهار الشعار',type:'toggle'},{key:'show_tax',label:'إظهار الضريبة',type:'toggle'},{key:'show_cashier',label:'إظهار الكاشير',type:'toggle'},{key:'show_customer',label:'إظهار العميل',type:'toggle'},{key:'show_barcode',label:'إظهار الباركود',type:'toggle'},{key:'footer',label:'رسالة أسفل الإيصال',type:'text'}]},
 {key:'dashboard',ar:'لوحة التحكم',en:'Dashboard',icon:<LayoutDashboard className="h-5 w-5"/>,fields:[{key:'default_range',label:'الفترة الافتراضية',type:'select',options:[['today','اليوم'],['week','7 أيام'],['month','30 يوم'],['year','السنة']]},{key:'show_sales',label:'مؤشر المبيعات',type:'toggle'},{key:'show_expenses',label:'مؤشر المصروفات',type:'toggle'},{key:'show_profit',label:'مؤشر الربح',type:'toggle'},{key:'show_inventory',label:'مؤشر المخزون',type:'toggle'},{key:'show_top_products',label:'أفضل المنتجات',type:'toggle'},{key:'show_recent_sales',label:'آخر المبيعات',type:'toggle'},{key:'show_payment_chart',label:'رسم طرق الدفع',type:'toggle'},{key:'show_employee_chart',label:'رسم أداء الموظفين',type:'toggle'}]},
 {key:'reports',ar:'التقارير',en:'Reports',icon:<BarChart3 className="h-5 w-5"/>,fields:[{key:'default_range',label:'الفترة الافتراضية',type:'select',options:[['today','اليوم'],['week','7 أيام'],['month','30 يوم'],['year','السنة']]},{key:'default_rows',label:'عدد الصفوف الافتراضي',type:'number'},{key:'show_zero_rows',label:'إظهار الصفوف بصفر',type:'toggle'},{key:'allow_export_excel',label:'السماح بتصدير Excel',type:'toggle'},{key:'allow_export_pdf',label:'السماح بتصدير PDF',type:'toggle'},{key:'allow_print',label:'السماح بالطباعة',type:'toggle'}]},
 {key:'notifications',ar:'التنبيهات',en:'Notifications',icon:<Bell className="h-5 w-5"/>,fields:[{key:'low_stock',label:'تنبيه المخزون المنخفض',type:'toggle'},{key:'shift_open',label:'تنبيه فتح الوردية',type:'toggle'},{key:'shift_close',label:'تنبيه إغلاق الوردية',type:'toggle'},{key:'purchase_due',label:'تنبيه استحقاق المشتريات',type:'toggle'},{key:'customer_due',label:'تنبيه مديونية العملاء',type:'toggle'}]},
 {key:'security',ar:'الأمان والجلسات',en:'Security',icon:<ShieldCheck className="h-5 w-5"/>,fields:[{key:'session_timeout_minutes',label:'مدة الجلسة بالدقائق',type:'number'},{key:'max_login_attempts',label:'أقصى محاولات تسجيل الدخول',type:'number'},{key:'lockout_minutes',label:'مدة القفل بالدقائق',type:'number'},{key:'require_password_change',label:'إجبار تغيير كلمة المرور',type:'toggle'},{key:'audit_all_changes',label:'تسجيل كل التغييرات في السجل',type:'toggle'}]},
 {key:'ui',ar:'واجهة النظام',en:'Interface',icon:<Palette className="h-5 w-5"/>,fields:[{key:'compact_tables',label:'جداول مضغوطة',type:'toggle'},{key:'animations',label:'الحركات والانتقالات',type:'toggle'},{key:'confirm_delete',label:'تأكيد قبل الحذف',type:'toggle'},{key:'confirm_post',label:'تأكيد قبل الترحيل',type:'toggle'},{key:'rtl',label:'واجهة RTL',type:'toggle'},{key:'show_help',label:'إظهار المساعدة',type:'toggle'}]},
];

function mergeConfig(raw: unknown): Config { const input = (raw && typeof raw === 'object' ? raw : {}) as Config; const out: Config = {}; for (const s of sections) out[s.key] = { ...DEFAULT_CONFIG[s.key], ...(input[s.key] || {}) }; return out; }

export function SystemControlCenterPage() {
 const { lang } = useLanguage(); const { show } = useToast(); const ar = lang === 'ar';
 const [config,setConfig] = useState<Config>(DEFAULT_CONFIG); const [active,setActive] = useState('general'); const [loading,setLoading] = useState(true); const [saving,setSaving] = useState(false); const [dirty,setDirty] = useState(false); const [query,setQuery] = useState('');
 useEffect(()=>{ supabase.from('system_settings').select('config').eq('id',1).maybeSingle().then(({data,error})=>{ if(error) show(error.message,'error'); if(data?.config) setConfig(mergeConfig(data.config)); setLoading(false); }); },[show]);
 const current = sections.find(s=>s.key===active) || sections[0];
 const filtered = useMemo(()=>{ const q=query.trim().toLowerCase(); if(!q) return sections; return sections.filter(s=>`${s.ar} ${s.en} ${s.fields.map(f=>f.label).join(' ')}`.toLowerCase().includes(q)); },[query]);
 const setValue=(section:string,key:string,value:string|number|boolean)=>{ setConfig(prev=>({...prev,[section]:{...prev[section],[key]:value}})); setDirty(true); };
 const save=async()=>{ setSaving(true); const {error}=await supabase.from('system_settings').upsert({id:1,config,updated_at:new Date().toISOString()},{onConflict:'id'}); setSaving(false); if(error){show(error.message,'error');return;} setDirty(false); show(ar?'تم حفظ إعدادات النظام بالكامل':'System settings saved','success'); };
 const reset=()=>{ setConfig(DEFAULT_CONFIG); setDirty(true); };
 if(loading) return <div className="flex min-h-[60vh] items-center justify-center"><div className="h-10 w-10 animate-spin rounded-full border-4 border-slate-200 border-t-brand-600"/></div>;
 return <div className="space-y-5 pb-10">
  <div className="rounded-3xl bg-gradient-to-br from-slate-950 via-navy-900 to-slate-800 p-6 text-white shadow-xl"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-2 flex items-center gap-2 text-sm text-gold-300"><SlidersHorizontal className="h-4 w-4"/>System Control Center</div><h1 className="text-3xl font-bold">{ar?'مركز التحكم الكامل بالنظام':'Complete System Control Center'}</h1><p className="mt-2 max-w-3xl text-sm text-slate-300">{ar?'تحكم في قواعد التشغيل والمبيعات والمخزون والتقارير والطباعة والواجهة والأمان من مكان واحد.':'Configure business rules, POS, inventory, reports, printing, interface and security from one place.'}</p></div><div className="flex gap-2"><Link to="/settings/basic" className="rounded-xl border border-white/20 px-4 py-2 text-sm hover:bg-white/10">{ar?'الإعدادات الحالية':'Existing Settings'}</Link><Button onClick={save} disabled={saving||!dirty}><Save className="h-4 w-4"/>{saving?(ar?'جارٍ الحفظ':'Saving...'):(ar?'حفظ كل الإعدادات':'Save All')}</Button></div></div></div>
  <div className="grid gap-5 lg:grid-cols-[270px_1fr]">
   <Card className="h-fit p-3"><div className="mb-3"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={ar?'بحث في الإعدادات...':'Search settings...'} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm outline-none focus:border-brand-500 dark:border-navy-700 dark:bg-navy-800"/></div><div className="space-y-1">{filtered.map(s=><button key={s.key} onClick={()=>setActive(s.key)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-start text-sm font-semibold transition ${active===s.key?'bg-brand-600 text-white shadow':'text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-navy-800'}`}>{s.icon}<span className="flex-1">{ar?s.ar:s.en}</span></button>)}</div></Card>
   <Card className="p-5"><div className="mb-5 flex items-center gap-3 border-b border-slate-100 pb-4 dark:border-navy-800">{current.icon}<div><h2 className="text-xl font-bold text-slate-900 dark:text-white">{ar?current.ar:current.en}</h2><p className="text-xs text-slate-400">{ar?'كل تغيير يتم حفظه في إعدادات النظام المركزية':'All changes are stored in centralized system settings.'}</p></div></div><div className="grid gap-4 md:grid-cols-2">{current.fields.map(field=>{const value=config[current.key]?.[field.key]; return <div key={field.key} className="rounded-2xl border border-slate-200 p-4 dark:border-navy-700"><div className="flex items-start justify-between gap-4"><div><label className="font-semibold text-slate-800 dark:text-slate-100">{field.label}</label>{field.help&&<p className="mt-1 text-xs text-slate-400">{field.help}</p>}</div>{field.type==='toggle'&&<button onClick={()=>setValue(current.key,field.key,!Boolean(value))} className={`relative h-6 w-11 rounded-full transition ${Boolean(value)?'bg-brand-600':'bg-slate-300 dark:bg-navy-700'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${Boolean(value)?'left-6':'left-1'}`}/></button>}</div>{field.type==='number'&&<input type="number" value={Number(value??0)} onChange={e=>setValue(current.key,field.key,Number(e.target.value))} className="mt-3 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 dark:border-navy-700 dark:bg-navy-800"/>}{field.type==='text'&&<input value={String(value??'')} onChange={e=>setValue(current.key,field.key,e.target.value)} className="mt-3 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 dark:border-navy-700 dark:bg-navy-800"/>}{field.type==='select'&&<select value={String(value??'')} onChange={e=>setValue(current.key,field.key,e.target.value)} className="mt-3 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 dark:border-navy-700 dark:bg-navy-800">{field.options?.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>}{field.type==='toggle'&&<div className="mt-2 text-xs text-slate-400">{Boolean(value)?(ar?'مفعّل':'Enabled'):(ar?'معطّل':'Disabled')}</div>}</div>})}</div></Card>
  </div>
  <Card className="p-5"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h3 className="font-bold text-slate-900 dark:text-white">{ar?'إدارة الوحدات الحالية':'Existing Modules'}</h3><p className="text-sm text-slate-400">{ar?'الإعدادات المركزية تتحكم في السلوك، وهذه الروابط لإدارة البيانات نفسها.':'Central settings control behavior; these links manage the actual data.'}</p></div><div className="flex flex-wrap gap-2">{[['/branches','الفروع'],['/users','المستخدمون'],['/products','المنتجات'],['/categories','الأقسام'],['/warehouses','المستودعات'],['/recipes','الوصفات'],['/reports','التقارير'],['/audit-log','سجل التدقيق']].map(([href,label])=><Link key={href} to={href} className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold hover:border-brand-400 dark:border-navy-700">{label}</Link>)}</div></div><div className="mt-5 flex items-center justify-between border-t pt-4 dark:border-navy-800"><span className="text-sm text-slate-500">{dirty?(ar?'هناك تغييرات غير محفوظة':'Unsaved changes'):(ar?'كل التغييرات محفوظة':'All changes saved')}</span><div className="flex gap-2"><button onClick={reset} className="rounded-xl border border-slate-200 px-4 py-2 text-sm dark:border-navy-700">{ar?'إرجاع الافتراضي':'Reset defaults'}</button><Button onClick={save} disabled={saving||!dirty}><Check className="h-4 w-4"/>{ar?'حفظ':'Save'}</Button></div></div></Card>
 </div>;
}
