import { ArrowLeft, Banknote, CreditCard, Smartphone, FileText, Tag, UtensilsCrossed, Users, CheckCircle2 } from 'lucide-react';
import { useLanguage } from '@/context/LanguageContext';
import { Button } from '@/components/Button';
import { formatCurrency } from '@/lib/format';
import type { PosPaymentMethod } from '@/lib/posMath';
import type { Customer, DiningTable, OrderType } from '@/lib/types';
import { orderTypeLabel } from '../../utils/format';
interface PaymentPanelProps { currentBranchName:string;orderType:OrderType;activeTable:DiningTable|null;activeOrderNumber:string|null;guestCount:number|null;onGuestCountChange:(n:number|null)=>void;customerId:string;customers:Customer[];onCustomerChange:(id:string)=>void;discountType:'amount'|'percent';discountAmount:number;onDiscountTypeChange:(v:'amount'|'percent')=>void;onDiscountAmountChange:(v:number)=>void;paymentMethod:PosPaymentMethod;onPaymentMethodChange:(m:PosPaymentMethod)=>void;paidAmount:number;onPaidAmountChange:(v:number)=>void;subtotal:number;discountValue:number;taxAmount:number;total:number;change:number;completing:boolean;canComplete:boolean;onComplete:()=>void;onBack:()=>void;currency:string; }
const METHODS:PosPaymentMethod[]=['cash','card','transfer','credit'];
const ICONS:Record<PosPaymentMethod,React.ReactNode>={cash:<Banknote className="h-6 w-6"/>,card:<CreditCard className="h-6 w-6"/>,transfer:<Smartphone className="h-6 w-6"/>,credit:<FileText className="h-6 w-6"/>};
export function PaymentPanel(p:PaymentPanelProps){const{t,lang}=useLanguage();const isAr=lang==='ar';const round=Math.ceil((p.total||0)/50)*50;const quick=[50,100,200,500];return <div className="flex h-full min-h-0 flex-col bg-slate-50 dark:bg-navy-950">
 <div className="flex items-center justify-between border-b bg-white px-4 py-4 dark:border-navy-800 dark:bg-navy-900"><button onClick={p.onBack} className="flex h-11 w-11 items-center justify-center rounded-xl hover:bg-slate-100 dark:hover:bg-navy-800"><ArrowLeft className={`h-5 w-5 ${isAr?'':'rotate-180'}`}/></button><div className="text-center"><p className="text-xs font-bold text-slate-400">{t('payOrder')}</p><p className="text-lg font-black text-slate-900 dark:text-white">{p.activeOrderNumber?`#${p.activeOrderNumber}`:''}</p></div><div className="w-11"/></div>
 <div className="min-h-0 flex-1 overflow-y-auto p-4"><div className="mx-auto max-w-2xl space-y-4">
  <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-navy-800 dark:bg-navy-900"><div className="flex flex-wrap items-center gap-3 text-sm font-black text-slate-700 dark:text-slate-200"><Tag className="h-5 w-5 text-gold-500"/>{p.currentBranchName}<span className="rounded-xl bg-slate-100 px-3 py-1.5 dark:bg-navy-800">{orderTypeLabel(t,p.orderType)}</span>{p.activeTable&&<span className="flex items-center gap-1 rounded-xl bg-emerald-50 px-3 py-1.5 text-emerald-700 dark:bg-emerald-900/20 dark:text-emerald-300"><UtensilsCrossed className="h-4 w-4"/>{p.activeTable.name}</span>}</div>{p.orderType==='dine_in'&&<label className="mt-4 flex items-center gap-2 text-xs font-bold text-slate-500"><Users className="h-4 w-4"/>{isAr?'عدد الأشخاص':'Guests'}<input type="number" min={1} value={p.guestCount||''} onChange={e=>p.onGuestCountChange(parseInt(e.target.value)||null)} className="w-20 rounded-xl border border-slate-200 px-3 py-2 text-center dark:border-navy-700 dark:bg-navy-800 dark:text-white"/></label>}</div>
  <div className="grid grid-cols-2 gap-3">{METHODS.map(m=><button data-testid={`pos-payment-method-${m}`} key={m} onClick={()=>p.onPaymentMethodChange(m)} className={`flex min-h-24 flex-col items-center justify-center gap-2 rounded-2xl border-2 bg-white text-sm font-black shadow-sm transition active:scale-[.98] dark:bg-navy-900 ${p.paymentMethod===m?'border-gold-500 bg-gold-50/50 text-gold-700 shadow-lg dark:bg-gold-900/10 dark:text-gold-300':'border-slate-200 text-slate-600 dark:border-navy-800 dark:text-slate-300'}`}>{ICONS[m]}{t(m)}{p.paymentMethod===m&&<CheckCircle2 className="h-4 w-4 text-gold-500"/>}</button>)}</div>
  {p.paymentMethod!=='credit'&&<div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-navy-800 dark:bg-navy-900"><label className="mb-2 block text-xs font-black text-slate-500">{t('paid')}</label><input type="number" value={p.paidAmount||''} onChange={e=>p.onPaidAmountChange(parseFloat(e.target.value)||0)} className="h-16 w-full rounded-2xl border border-slate-200 bg-slate-50 text-center text-3xl font-black text-slate-900 outline-none focus:border-gold-500 focus:ring-2 focus:ring-gold-500/20 dark:border-navy-700 dark:bg-navy-800 dark:text-white"/><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>p.onPaidAmountChange(p.total)} className="rounded-xl bg-emerald-100 px-4 py-2.5 text-xs font-black text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300">{isAr?'بالضبط':'Exact'}</button><button onClick={()=>p.onPaidAmountChange(round)} className="rounded-xl bg-slate-100 px-4 py-2.5 text-xs font-black text-slate-700 dark:bg-navy-800 dark:text-slate-300">{formatCurrency(round,p.currency,lang)}</button>{quick.map(v=><button key={v} onClick={()=>p.onPaidAmountChange(p.paidAmount+v)} className="rounded-xl bg-slate-100 px-4 py-2.5 text-xs font-black text-slate-700 dark:bg-navy-800 dark:text-slate-300">+{v}</button>)}</div>{p.change>0&&<div className="mt-3 flex justify-between rounded-2xl bg-emerald-50 p-4 text-sm font-black text-emerald-700 dark:bg-emerald-900/20 dark:text-emerald-300"><span>{t('change')}</span><span>{formatCurrency(p.change,p.currency,lang)}</span></div>}</div>}
 </div></div>
 <div className="border-t bg-white p-4 dark:border-navy-800 dark:bg-navy-900"><div className="mx-auto max-w-2xl"><div className="mb-3 flex items-end justify-between"><span className="text-sm font-bold text-slate-500">{t('total')}</span><span className="text-3xl font-black text-gold-500">{formatCurrency(p.total,p.currency,lang)}</span></div><Button data-testid="pos-payment-confirm" size="lg" className="w-full !min-h-14 !rounded-2xl !bg-emerald-600 text-lg font-black shadow-xl shadow-emerald-600/20" onClick={p.onComplete} disabled={p.completing||!p.canComplete}>{p.completing?(isAr?'جاري المعالجة...':'Processing...'):(isAr?'تأكيد الدفع':'Confirm Payment')}</Button></div></div>
 </div>};
